/**
 * _gen-router-sh <manifest> —— 内部命令（BACKLOG #19 接线）。
 * 从 templates/manifest.yaml 派生 router.sh 所需的 bash 缓存（评分正则 + breadcrumb + skill 变量），
 * 与 hooks/router-gen.mjs 输出**逐字等价**——router.sh 优先调本命令（bundle 自含 kernel、安装态最稳），
 * 失败回退自带 mjs。非用户命令（`_` 前缀），不进 help 主流程。
 */
import { readFileSync } from 'node:fs'
import { loadManifest, genRouterSh, skillsFor } from '@pipeline-lite/kernel'
import type { CliDeps } from '../deps.js'

/** bash 单引号安全包裹（对齐 kernel manifest.ts::bashSquote / router-gen.mjs::sq） */
function sq(s: string): string {
  return `'${String(s).replace(/'/g, "'\\''")}'`
}

/** 合法 bash 变量名片段（phase/track 为已知小写枚举，仍白名单化防注入） */
function safeSeg(s: string): boolean {
  return /^[A-Za-z_][A-Za-z0-9_]*$/.test(s)
}

const GEN_TRACKS = ['pm', 'frontend', 'backend'] as const

export async function cmdGenRouterSh(deps: CliDeps, manifestPath: string | undefined): Promise<number> {
  if (!manifestPath) {
    deps.io.err('_gen-router-sh: 缺 manifest 路径参数')
    return 2
  }
  try {
    readFileSync(manifestPath, 'utf8') // fail-loud 提前定位不可读
    const m = loadManifest(manifestPath)
    const out: string[] = ['# AUTO-GENERATED by pipeline _gen-router-sh from templates/manifest.yaml — 勿手改']
    out.push(genRouterSh(m.routerPatterns))
    for (const phase of m.phases) {
      if (!safeSeg(phase)) continue
      const bc = m.breadcrumbs[phase]
      if (bc !== undefined) out.push(`BREADCRUMB_${phase}=${sq(bc)}`)
    }
    for (const phase of m.phases) {
      if (!safeSeg(phase)) continue
      for (const track of GEN_TRACKS) {
        const rec = skillsFor(m.recommendedSkills, phase, track)
        const mand = skillsFor(m.mandatorySkills, phase, track)
        if (rec.length) out.push(`RECSKILL_${phase}_${track}=${sq(rec.join(', '))}`)
        if (mand.length) out.push(`MANDSKILL_${phase}_${track}=${sq(mand.join(', '))}`)
      }
    }
    deps.io.out(out.join('\n'))
    return 0
  } catch (e) {
    deps.io.err(`_gen-router-sh: ${e instanceof Error ? e.message : String(e)}`)
    return 2
  }
}
