import { randomUUID } from 'node:crypto'
import { chmod, lstat, mkdir, open, readFile, realpath, rename, rm } from 'node:fs/promises'
import { dirname, isAbsolute, join, relative, resolve } from 'node:path'
import { parseSkillSources } from '@tenon/kernel'
import { buildCanonicalManifest, verifySkillProvenance } from '@tenon/automation'
import type { CliDeps } from '../deps.js'

export type SkillProvenanceCommandMode = 'verify' | 'sync'

export interface InternalSkillProvenanceOptions {
  readonly root?: string
  readonly json?: boolean
  readonly quiet?: boolean
}

function rootPath(value: string | undefined): string {
  if (value === undefined || value.trim() === '') throw new Error('--root <path> 是必需参数')
  return resolve(value)
}

function within(root: string, path: string): boolean {
  const rel = relative(root, path)
  return rel === '' || (!rel.startsWith('../') && rel !== '..' && !rel.includes('/../'))
}

function quoteValue(value: string): string {
  return /[\s,{}:#"']/.test(value) ? JSON.stringify(value) : value
}

function renderEntry(entry: ReturnType<typeof parseSkillSources>[number], digest: string): string {
  const physical = entry.contentSkill ?? entry.token
  const fields: string[] = [
    `tool: ${entry.tool}`,
    `source: ${quoteValue(entry.source)}`,
  ]
  if (entry.skill !== undefined) fields.push(`skill: ${quoteValue(entry.skill)}`)
  if (entry.contentSkill !== undefined) fields.push(`content_skill: ${quoteValue(entry.contentSkill)}`)
  fields.push(`tier: ${entry.tier}`, `official: ${entry.official ? 'true' : 'false'}`)
  if (entry.engine !== undefined) fields.push(`engine: ${quoteValue(entry.engine)}`)
  if (entry.bin !== undefined) fields.push(`bin: ${quoteValue(entry.bin)}`)
  if (entry.unavailable !== undefined) fields.push(`unavailable: ${entry.unavailable ? 'true' : 'false'}`)
  if (entry.alt !== undefined) fields.push(`alt: ${quoteValue(entry.alt)}`)
  if (entry.note !== undefined) fields.push(`note: ${quoteValue(entry.note)}`)
  const sourceRef = `skills/${physical}`
  const contentHash = `sha256:${digest}`
  fields.push('source_kind: bundled', `source_ref: ${sourceRef}`, `content_hash: ${contentHash}`)
  fields.push(`coordinate: tenon:${sourceRef}@${contentHash}`)
  return `  ${entry.token}: { ${fields.join(', ')} }`
}

function renderRegistry(entries: readonly { entry: ReturnType<typeof parseSkillSources>[number]; digest: string }[]): string {
  const lines = [
    '# templates/skill-sources.yaml — canonical Skill provenance registry',
    '# Generated by tenon internal-skill-provenance sync; edit Skill bytes then rerun sync.',
    'version: 3',
    'hash_algorithm: tree-sha256-v1',
    '',
    'skills:',
    ...entries.map(({ entry, digest }) => renderEntry(entry, digest)),
    '',
  ]
  return lines.join('\n')
}

async function assertCanonicalRegistryPath(root: string, registryPath: string): Promise<void> {
  const canonicalRoot = await realpath(root)
  const templatesPath = dirname(registryPath)
  const templatesStat = await lstat(templatesPath)
  if (!templatesStat.isDirectory() || templatesStat.isSymbolicLink()) {
    throw new Error(`canonical registry parent 不是 root 内的普通目录: ${templatesPath}`)
  }
  const canonicalTemplates = await realpath(templatesPath)
  if (!within(canonicalRoot, canonicalTemplates)) {
    throw new Error(`canonical registry parent 越出 --root: ${templatesPath}`)
  }
  try {
    const registryStat = await lstat(registryPath)
    if (!registryStat.isFile() || registryStat.isSymbolicLink()) {
      throw new Error(`canonical registry 不是 root 内的普通文件: ${registryPath}`)
    }
    const canonicalRegistry = await realpath(registryPath)
    if (!within(canonicalRoot, canonicalRegistry)) {
      throw new Error(`canonical registry 越出 --root: ${registryPath}`)
    }
  } catch (error) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return
    throw error
  }
}

async function syncRegistry(root: string): Promise<{ readonly registryPath: string; readonly count: number }> {
  const registryPath = join(root, 'templates', 'skill-sources.yaml')
  if (!within(root, registryPath)) throw new Error('registry path 越出 --root')
  await assertCanonicalRegistryPath(root, registryPath)
  const sourceText = await readFile(registryPath, 'utf8')
  const entries = parseSkillSources(sourceText)
  const computed: Array<{ entry: ReturnType<typeof parseSkillSources>[number]; digest: string }> = []
  for (const entry of entries) {
    if (entry.tool !== 'bundled' || entry.source !== 'tenon') {
      throw new Error(`token '${entry.token}' 不是 bundled/tenon provenance，拒绝 sync`)
    }
    const physical = entry.contentSkill ?? entry.token
    if (physical.includes('/') || physical.includes('\\') || physical === '.' || physical === '..' || physical.includes('\0')) {
      throw new Error(`token '${entry.token}' content_skill 路径不安全`)
    }
    const manifest = await buildCanonicalManifest(physical, join(root, 'skills', physical))
    computed.push({ entry, digest: manifest.treeSha256 })
  }
  const output = renderRegistry(computed)
  const tmp = `${registryPath}.tmp-${process.pid}-${randomUUID()}`
  let handle
  try {
    await mkdir(dirname(registryPath), { recursive: true })
    handle = await open(tmp, 'wx', 0o644)
    await handle.writeFile(output, 'utf8')
    await handle.sync()
    await handle.close()
    handle = undefined
    await rename(tmp, registryPath)
    await chmod(registryPath, 0o644)
  } catch (error) {
    if (handle !== undefined) await handle.close().catch(() => undefined)
    await rm(tmp, { force: true }).catch(() => undefined)
    throw error
  }
  return { registryPath, count: computed.length }
}

function renderFindings(result: Awaited<ReturnType<typeof verifySkillProvenance>>): string[] {
  return result.findings.map((item) => {
    const subject = item.skill === undefined ? '' : ` skill=${item.skill}`
    const values = item.expected === undefined && item.actual === undefined
      ? ''
      : ` expected=${item.expected ?? '-'} actual=${item.actual ?? '-'}`
    return `[${item.category}]${subject}${values} ${item.detail}；修复：${item.remediation}`
  })
}

/** Hidden bundled CLI command used by setup, CI, release candidate verification and authoring. */
export async function cmdInternalSkillProvenance(
  deps: CliDeps,
  mode: string,
  options: InternalSkillProvenanceOptions,
): Promise<number> {
  if (mode !== 'verify' && mode !== 'sync') {
    deps.io.err(`internal-skill-provenance: unsupported mode '${mode}'（支持 verify|sync）`)
    return 2
  }
  let root: string
  try {
    root = rootPath(options.root)
  } catch (error) {
    deps.io.err(`internal-skill-provenance: ${error instanceof Error ? error.message : String(error)}`)
    return 2
  }

  if (mode === 'sync') {
    try {
      const result = await syncRegistry(root)
      if (!options.quiet) {
        if (options.json) deps.io.out(JSON.stringify({ ok: true, ...result }))
        else deps.io.out(`skill provenance sync: ${result.count} entries → ${result.registryPath}`)
      }
      return 0
    } catch (error) {
      const message = `internal-skill-provenance sync failed: ${error instanceof Error ? error.message : String(error)}`
      if (options.json) deps.io.err(JSON.stringify({ ok: false, findings: [{ category: 'filesystem-safety-error', detail: message }] }))
      else deps.io.err(message)
      return 1
    }
  }

  const result = await verifySkillProvenance(root)
  if (result.ok) {
    if (options.json && !options.quiet) deps.io.out(JSON.stringify({ ok: true, root }))
    else if (!options.quiet) deps.io.out(`skill provenance verify: OK (${root})`)
    return 0
  }
  if (options.json) deps.io.err(JSON.stringify({ ok: false, root, findings: result.findings }))
  else for (const line of renderFindings(result)) deps.io.err(`internal-skill-provenance: ${line}`)
  return 1
}

export { syncRegistry as syncSkillProvenanceRegistry }
