import { digestAggregate, evolveV2 } from './v2-evolve.js'
import type { BoardCommandV2, BoardEventV2, OrchestrationAggregateV2, SkillRunV2, V2Decision, V2Rejection } from './v2-types.js'

function reject(code: V2Rejection['code'], message: string, reasonCode: string = code, nextActions: readonly string[] = []): V2Decision {
  return { ok: false, rejection: { code, message, reason_code: reasonCode, next_actions: nextActions } }
}
function find<T extends object>(items: readonly T[], key: keyof T, id: unknown): T | undefined { return items.find((entry) => entry[key] === id) }
function isTerminal(status: OrchestrationAggregateV2['status']): boolean { return status === 'completed' || status === 'cancelled' }
function activeLease(aggregate: OrchestrationAggregateV2, runId: string): SkillRunV2['lease'] | undefined { return find(aggregate.runs, 'run_id', runId)?.lease }
function leaseMatches(aggregate: OrchestrationAggregateV2, runId: string, leaseId: string, ownerId: string, generation: number): boolean { const lease = activeLease(aggregate, runId); return lease !== undefined && lease.lease_id === leaseId && lease.owner_id === ownerId && (lease.generation === generation || lease.generation + 1 === generation) && (lease.status === 'active' || lease.status === 'renewed') }

function stateGuard(aggregate: OrchestrationAggregateV2, command: BoardCommandV2): V2Decision | undefined {
  switch (command.type) {
    case 'accept-request': if (aggregate.status !== 'draft' || aggregate.request !== undefined) return reject('invalid-transition', 'request can only be accepted once from draft', 'request-order'); break
    case 'record-context': if (aggregate.status !== 'draft' || aggregate.request === undefined || aggregate.context !== undefined) return reject('invalid-transition', 'context requires an accepted request and an empty context', 'context-order', ['accept-request']); break
    case 'record-assessment': if (aggregate.status !== 'assessing' || aggregate.context === undefined || aggregate.assessment !== undefined) return reject('invalid-transition', 'assessment requires the current repository context', 'assessment-order', ['record-context']); break
    case 'freeze-work-graph': if (aggregate.status !== 'planning' || aggregate.assessment?.normalization !== 'complete' || command.graph.status !== 'frozen') return reject('invalid-transition', 'only a complete assessment can freeze a graph', 'graph-order', ['record-assessment']); break
    case 'resolve-capabilities': if (aggregate.status !== 'planned' || aggregate.graph?.status !== 'frozen') return reject('invalid-transition', 'capabilities require a frozen graph', 'resolution-order', ['freeze-work-graph']); break
    case 'start-change': if (aggregate.status !== 'ready' || aggregate.work_items.length === 0 || aggregate.work_items.some((item) => item.status === 'blocked' || item.status === 'cancelled')) return reject('policy-blocked', 'change has no runnable work', 'scheduler-not-ready', ['resolve-capabilities']); break
    case 'enqueue-work-item': { const item = find(aggregate.work_items, 'work_item_id', command.work_item_id); if (item === undefined) return reject('not-found', 'work item not found', 'work-item-not-found'); if (!['ready', 'interrupted', 'failed', 'blocked'].includes(item.status)) return reject('invalid-transition', 'work item cannot be enqueued from its current state', 'work-item-state'); break }
    case 'claim-run': { const item = find(aggregate.work_items, 'work_item_id', command.run.work_item_id); if (item === undefined) return reject('not-found', 'work item not found', 'work-item-not-found'); if (item.status !== 'queued') return reject('invalid-transition', 'only queued work items can be claimed', 'work-item-not-queued'); if (command.run.status !== 'queued' || command.run.attempt < 1 || command.lease.generation !== 1) return reject('contract-invalid', 'a first claim requires a queued run and generation-one lease', 'claim-contract'); const active = item.active_run_id === undefined ? undefined : find(aggregate.runs, 'run_id', item.active_run_id); if (item.active_run_id !== undefined && item.active_run_id !== command.run.run_id) return reject('policy-blocked', 'work item is reserved for a different queued run', 'lease-conflict'); if (active !== undefined && active.status !== 'queued') return reject('policy-blocked', 'work item already has an active run', 'lease-conflict'); if (aggregate.runs.some((run) => run.work_item_id === item.work_item_id && (run.status === 'claimed' || run.status === 'running'))) return reject('policy-blocked', 'work item already has an active run', 'lease-conflict'); break }
    case 'heartbeat-run': { const run = find(aggregate.runs, 'run_id', command.run_id); const lease = run?.lease; if (run === undefined || lease === undefined) return reject('not-found', 'run or lease not found', 'run-not-found'); if (!leaseMatches(aggregate, command.run_id, command.lease_id, command.owner_id, command.generation)) return reject('lease-mismatch', 'heartbeat lease identity is stale', 'lease-generation-mismatch', ['reclaim-run']); if (command.generation !== lease.generation + 1) return reject('lease-mismatch', 'heartbeat generation must increase by exactly one', 'lease-generation-not-monotonic', ['reload-snapshot']); break }
    case 'begin-run': { const run = find(aggregate.runs, 'run_id', command.run_id); if (run === undefined) return reject('not-found', 'run not found', 'run-not-found'); if (run.status !== 'claimed') return reject('invalid-transition', 'only claimed runs can begin', 'run-order'); if (!leaseMatches(aggregate, command.run_id, command.lease_id, command.owner_id, command.generation)) return reject('lease-mismatch', 'begin lease identity is stale', 'lease-generation-mismatch'); break }
    case 'complete-run': { const run = find(aggregate.runs, 'run_id', command.run_id); if (run === undefined) return reject('not-found', 'run not found', 'run-not-found'); if (run.status !== 'running') return reject('invalid-transition', 'only running runs can complete', 'run-order'); if (run.lease === undefined || !leaseMatches(aggregate, command.run_id, run.lease.lease_id, run.lease.owner_id, run.lease.generation)) return reject('lease-mismatch', 'complete requires the active run lease', 'lease-generation-mismatch'); if (command.result.run_id !== command.run_id || command.result.contract_status === 'invalid') return reject('contract-invalid', 'result does not match run or is invalid', 'result-contract-invalid'); break }
    case 'record-validation': { const result = find(aggregate.results, 'result_id', command.report.result_id); const item = find(aggregate.work_items, 'work_item_id', command.report.work_item_id); const run = result === undefined ? undefined : find(aggregate.runs, 'run_id', result.run_id); if (result === undefined || item === undefined || run === undefined || run.status !== 'completed') return reject('missing-evidence', 'validation requires a completed matching run result', 'validation-evidence-missing', ['complete-run']); break }
    case 'evaluate-gate': if (command.gate.status === 'waived' && (command.gate.actor.kind !== 'user' || command.gate.rationale === undefined || command.gate.waiver_receipt_ref === undefined)) return reject('policy-blocked', 'gate waiver requires user rationale and receipt', 'waiver-policy'); if (command.gate.status === 'passed' && command.gate.required_evidence_refs.some((ref) => !aggregate.results.some((result) => result.artifacts.some((artifact) => artifact.ref === ref)) && !aggregate.validations.some((report) => report.evidence_refs.includes(ref)))) return reject('missing-evidence', 'gate evidence is not available', 'gate-evidence-missing'); break
    case 'pause-change': if (!['ready', 'executing', 'waiting-input', 'blocked'].includes(aggregate.status)) return reject('invalid-transition', 'change is not pausable from its current state', 'pause-state'); break
    case 'resume-change': if (aggregate.status !== 'paused') return reject('invalid-transition', 'only paused changes can resume', 'resume-state'); break
    case 'retry-work-item': { const item = find(aggregate.work_items, 'work_item_id', command.work_item_id); if (item === undefined || !['failed', 'interrupted', 'blocked'].includes(item.status)) return reject('invalid-transition', 'only failed, interrupted, or blocked items can retry', 'retry-state'); if (aggregate.runs.some((run) => run.run_id === command.run_id || run.attempt_id === command.attempt_id)) return reject('idempotency-conflict', 'retry must create a new run and attempt identity', 'retry-lineage-conflict'); break }
    case 'cancel-change': break
    case 'replan-change': if (isTerminal(aggregate.status)) return reject('terminal-state', 'terminal change cannot replan', 'terminal-state'); break
    case 'bind-artifact': if (find(aggregate.work_items, 'work_item_id', command.work_item_id) === undefined) return reject('not-found', 'work item not found', 'work-item-not-found'); break
  }
  return undefined
}

export function decideV2(aggregate: OrchestrationAggregateV2, command: BoardCommandV2): V2Decision {
  if (isTerminal(aggregate.status)) return reject('terminal-state', `terminal change rejects ${command.type}`, 'terminal-state')
  if (command.change_id !== aggregate.change_id) return reject('contract-invalid', 'command change does not match aggregate', 'identity-mismatch')
  if (command.correlation_id !== aggregate.correlation_id) return reject('contract-invalid', 'correlation chain does not match aggregate', 'causal-chain-mismatch')
  if (command.expected_revision !== aggregate.revision) return reject('revision-conflict', `expected revision ${command.expected_revision}, current ${aggregate.revision}`, 'stale-revision', ['reload-snapshot'])
  if (aggregate.command_head_id === command.command_id) return reject('idempotency-conflict', 'command already applied; repository should replay stored event', 'idempotent-replay')
  if (command.type === 'record-context' && aggregate.request?.request_id !== command.context.request_id) return reject('contract-invalid', 'context request mismatch', 'request-context-mismatch')
  if (command.type === 'record-assessment' && (aggregate.request === undefined || aggregate.context === undefined || aggregate.request.request_id !== command.assessment.request_id || command.assessment.context_record_id !== aggregate.context.record_id)) return reject('contract-invalid', 'assessment must bind request and context', 'assessment-binding-mismatch')
  if (command.type === 'freeze-work-graph' && (aggregate.assessment === undefined || command.graph.assessment_id !== aggregate.assessment.assessment_id)) return reject('contract-invalid', 'graph must bind assessment', 'graph-binding-invalid')
  if (command.type === 'resolve-capabilities' && (aggregate.graph === undefined || aggregate.assessment === undefined || command.resolution.graph_id !== aggregate.graph.graph_id || command.resolution.assessment_id !== aggregate.assessment.assessment_id)) return reject('contract-invalid', 'resolution must bind graph and assessment', 'resolution-binding-invalid')
  const guarded = stateGuard(aggregate, command)
  if (guarded !== undefined) return guarded
  const draft: BoardEventV2 = { schema_version: 'board-event/v2', event_id: `event:${command.command_id}`, event_type: command.type, command_id: command.command_id, idempotency_key: command.idempotency_key, project_id: aggregate.project_id, change_id: aggregate.change_id, correlation_id: aggregate.correlation_id, ...(command.causation_id === undefined ? {} : { causation_id: command.causation_id }), actor: command.actor, revision: aggregate.revision + 1, issued_at: command.issued_at, before_digest: digestAggregate(aggregate), after_digest: digestAggregate({ ...aggregate, revision: aggregate.revision + 1 }), payload: command, effects: command.type === 'cancel-change' ? aggregate.runs.filter((run) => run.status === 'claimed' || run.status === 'running').map((run) => ({ type: 'request-executor-cancel' as const, run_id: run.run_id })) : [{ type: 'wake-scheduler' as const, reason: command.type }] }
  const after = evolveV2(aggregate, draft)
  return { ok: true, event: { ...draft, after_digest: digestAggregate(after) } }
}
