/**
 * router-gen.mjs — router 派生缓存生成器（**非热路径**：仅当 templates/manifest.yaml
 * 比缓存新时，被 hooks/router.sh 调用一次；命中缓存时 router.sh 纯 source、绝不触达本文件）。
 *
 * 消费 #18 就绪的 kernel 派生（GOAL A2 单一真相源）：
 *   · genRouterSh(routerPatterns) → FE/BE/PM_PATTERN（router.sh score_track 用）
 *   · breadcrumbs[phase]          → BREADCRUMB_<phase>（每轮注入相位行动提示用）
 *   · skillsFor(recommended/mandatory, phase, track) → RECSKILL/MANDSKILL_<phase>_<track>
 * 逐字派生，零硬编码——改 manifest.yaml 即改缓存（回归锚见 tools/test-hooks.sh 的 router 段）。
 *
 * 输出：可被 bash `source` 的赋值脚本（单引号 squote 转义防注入，对齐老 manifest.py::_bash_squote）。
 * 用法：node router-gen.mjs <manifest.yaml 路径>   → stdout 打印 bash 缓存；任何异常 → 非零退出、无输出。
 *
 * CONTRACT §5.4 边界说明：热路径红线约束的是「每轮 UserPromptSubmit 都跑」的 cache-hit 路径
 * （router.sh 纯 bash source + 打分，零 node spawn）。本生成器只在 manifest mtime 变新时跑一次，
 * 属老仓 pipeline-router.sh 同款「mtime 缓存 + 变更时 spawn 一次」可接受模式。
 */
import { readFileSync } from 'node:fs'

// —— 解析 kernel（monorepo dist 优先；失败回退 bare specifier；再失败 → 抛出，router.sh fail-safe）——
async function loadKernel() {
  const candidates = [
    new URL('../packages/kernel/dist/index.js', import.meta.url).href, // monorepo 布局
    '@pipeline-lite/kernel', // node_modules 解析（bundle/安装态）
  ]
  let lastErr
  for (const spec of candidates) {
    try {
      return await import(spec)
    } catch (e) {
      lastErr = e
    }
  }
  throw lastErr ?? new Error('kernel 不可解析')
}

/** bash 单引号安全包裹（对齐 kernel manifest.ts::bashSquote / 老 manifest.py::_bash_squote） */
function sq(s) {
  return "'" + String(s).replace(/'/g, "'\\''") + "'"
}

/** 合法 bash 变量名片段（phase/track 均为已知小写枚举，仍白名单化防注入） */
function safeSeg(s) {
  return /^[A-Za-z_][A-Za-z0-9_]*$/.test(s)
}

async function main() {
  const manifestPath = process.argv[2]
  if (!manifestPath) {
    process.stderr.write('router-gen: 缺 manifest 路径参数\n')
    process.exit(2)
  }
  // 触发一次读取以在路径不可读时 fail-loud（loadManifest 内部也会读，这里提前定位错误）
  readFileSync(manifestPath, 'utf8')

  const k = await loadKernel()
  const m = k.loadManifest(manifestPath)

  const out = []
  out.push('# AUTO-GENERATED by hooks/router-gen.mjs from templates/manifest.yaml — 勿手改')
  // ① Track 评分正则（genRouterSh 逐字派生）
  out.push(k.genRouterSh(m.routerPatterns))
  // ② 每相位 breadcrumb prose（BREADCRUMB_<phase>）
  for (const phase of m.phases) {
    if (!safeSeg(phase)) continue
    const bc = m.breadcrumbs[phase]
    if (bc !== undefined) out.push(`BREADCRUMB_${phase}=${sq(bc)}`)
  }
  // ③ 每 phase×track 推荐 / 强制 skill（skillsFor 三级回退逐字派生；逗号连接）
  const tracks = ['pm', 'frontend', 'backend']
  for (const phase of m.phases) {
    if (!safeSeg(phase)) continue
    for (const track of tracks) {
      const rec = k.skillsFor(m.recommendedSkills, phase, track)
      const mand = k.skillsFor(m.mandatorySkills, phase, track)
      if (rec.length) out.push(`RECSKILL_${phase}_${track}=${sq(rec.join(', '))}`)
      if (mand.length) out.push(`MANDSKILL_${phase}_${track}=${sq(mand.join(', '))}`)
    }
  }
  process.stdout.write(out.join('\n') + '\n')
}

main().catch((e) => {
  process.stderr.write(`router-gen: ${e && e.message ? e.message : e}\n`)
  process.exit(1)
})
